const BASE_URL_V2 = process.env.REACT_APP_API_BASE_URL_V2;

export const inventory = {
  inboundList: `${BASE_URL_V2}inbound`,
  getDetailInbound: (id:string | string[]) => `${BASE_URL_V2}inbound/${id}`,
  createOrder: `${BASE_URL_V2}purchase-order/create`,
  listOrder: `${BASE_URL_V2}purchase-order`,
  editOrder: (id) => `${BASE_URL_V2}purchase-order/${id}`,
  orderDetail: (id) => `${BASE_URL_V2}purchase-order/${id}`,
  cancelOrder: (id) => `${BASE_URL_V2}purchase-order/${id}/cancel`,
  approveOrder: (id) => `${BASE_URL_V2}purchase-order/${id}/approve`,
  exportPurchaseOrder: `${BASE_URL_V2}purchase-order/export`,
  confirmationInbound: `${BASE_URL_V2}inbound/process-inbound`,
  listStock: `${BASE_URL_V2}stock`,
  detailStock: `${BASE_URL_V2}stock/detail`,
  historyStock: `${BASE_URL_V2}stock/history`,
  outboundList: `${BASE_URL_V2}outbound`,
  exportInbound: `${BASE_URL_V2}inbound/export`,
  getDetailOutbound: (id:string | string[]) => `${BASE_URL_V2}outbound/detail?id=${id}`,
  createTransfer: `${BASE_URL_V2}transfer`,
  editTransfer: (id) => `${BASE_URL_V2}transfer/${id}/change-info`,
  transferDetail: (id) => `${BASE_URL_V2}transfer/${id}`,
  transferList: `${BASE_URL_V2}transfer/search`,
  exportTranfer: `${BASE_URL_V2}transfer/export`,
  approveTransfer: (id) => `${BASE_URL_V2}transfer/${id}/approve`,
  cancelTransfer: (id) => `${BASE_URL_V2}transfer/${id}/cancel`,
  getFilterListTransfer: `${BASE_URL_V2}transfer/list-user`,
  stockListSku: `${BASE_URL_V2}stock/list`,
  adjustmentList: `${BASE_URL_V2}stock-adjustment`,
  createAdjustment: `${BASE_URL_V2}stock-adjustment/create`,
  adjustmentDetail: (id) => `${BASE_URL_V2}stock-adjustment/${id}`,
  editAdjustment: (id) => `${BASE_URL_V2}stock-adjustment/${id}`,
  approveAdjustment: (id) => `${BASE_URL_V2}stock-adjustment/${id}/approve`,
  cancelAdjustment: (id) => `${BASE_URL_V2}stock-adjustment/${id}/cancel`,
};